export const ingredients : string[] = [
    "Chicken",
    "Borlotti Beans",
    "Bowtie Pasta",
    "Bramley Apples",
    "Brandy",
    "Bread",
    "Breadcrumbs",
    "Broccoli",
    "Brown Lentils",
    "Brown Rice",
    "Brown Sugar",
    "Butter",
    "Cacao",
    "Cajun",
    "Canned Tomatoes",
    "Cannellini Beans",
    "Cardamom",
    "Carrots",
    "Cashew Nuts",
    "Cashews",
    "Caster Sugar",
    "Cayenne Pepper",
    "Celeriac",
    "Celery",
    "Celery Salt",
    "Challots",
    "Charlotte Potatoes",
    "Cheddar Cheese",
    "Cheese",
    "Cheese Curds",
    "Cherry Tomatoes",
    "Chestnut Mushroom",
    "Chicken Breast",
    "Chicken Breasts",
    "Chicken Legs",
    "Chicken Stock",
    "Chicken Thighs",
    "Chickpeas",
    "Chili Powder",
    "Chilled Butter",
    "Chilli",
    "Chinese Broccoli",
    "Chocolate Chips",
    "Chopped Onion",
    "Chopped Parsley",
    "Chopped Tomatoes",
    "Chorizo",
    "Christmas Pudding",
    "Cilantro",
    "Cinnamon",
    "Cinnamon Stick",
    "Cloves",
    "Coco Sugar",
    "Cocoa",
    "Coconut Cream",
    "Coconut Milk",
    "Colby Jack Cheese",
    "Cold Water",
    "Condensed Milk",
    "Coriander",
    "Coriander Leaves",
    "Coriander Seeds",
    "Corn Tortillas",
    "Cornstarch",
    "Cream",
    "Creme Fraiche",
  ];
  